name: AOC2017 
version: '0.0.0.1'
synopsis: Avent of Code 2017
description: ! '
  Avent of Code 2017
'
author: Jon Schoning
maintainer: jonschoning@gmail.com
copyright: Copyright (c) 2015 Jon Schoning
license: MIT
homepage: https://github.com/jonschoning/advent-of-code-2017
git: git://github.com/jonschoning/advent-of-code-2017.git
bug-reports: https://github.com/jonschoning/advent-of-code-2017/issues
ghc-options: -Wall -O2
dependencies:
- base >=4.7 && <5.0
- bytestring >=0.10.0
- containers
- mtl >=2.2.1
- safe-exceptions <0.2
- text >=0.11
- transformers >=0.4.0.0
- unordered-containers
- lens
- either
- attoparsec
library:
  source-dirs: src
  ghc-options:
  - -fno-warn-unused-binds 
  - -fno-warn-unused-imports

  exposed-modules:
  - Day1
  - Day2
  - Day3
  - Day4
  - Day5
  - Day6
  - Day7
  - Day8
  - Day9
  - Day10
  dependencies:
  - time >=1.5
  - vector >=0.10.9
  - random >=1.1
  - split
executables:
  AOC2017:
    main: app/Main.hs
    dependencies:
    - AOC2017
    - unix
    - deepseq
    - criterion
tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options:
    - -fno-warn-orphans
    dependencies:
    - AOC2017
    - hspec >=1.8
    - HUnit > 1.5.0
